import type { Metadata } from "next";
import localFont from "next/font/local";
import { Roboto } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignedIn, SignedOut } from "@clerk/nextjs";
import SignInBtn from "./components/SignInBtn";
import TopBar from "./components/TopBar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const roboto = Roboto({
  variable: "--font-roboto",
  weight: "400",
  preload: true,
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} antialiased grid min-h-[100dvh] grid-rows-[auto_1fr_auto]`}
        >
          <SignedOut>
            <div />
            <div className="flex justify-center items-center">
              <SignInBtn />
            </div>
          </SignedOut>
          <SignedIn>
            <TopBar />
            {children}
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}
